name: "setup-gpg"
description: "Installs the same version of gpg as on Travis CI"
author: "Olafur Pall Geirsson"
runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "download"
  color: "blue"
